### ISSUE TITLE
problem in test

### ISSUE THREAD

**Issue by kiyaaabdian** [laisimiao/ReFocus_TIR_Tracking#1]
hello i have a question, i want to test my dataset images with your networks, but it needs some other data for test, i can not find that why we should test it with specific dataset? if i can test my images, can you help me please?

**Comment by laisimiao** [comment]
what other data?

**Comment by kiyaaabdian** [comment]
for example in def run_tracker need dataset_name otb or lsotb_lt ,..

**Comment by laisimiao** [comment]
...
You can change it into your dataset name.
